---
title: "hw4 - plotly"
output: 
  flexdashboard::flex_dashboard:
    orientation: columns
    vertical_layout: fill
---

```{r setup, include=FALSE, echo = FALSE}
# rmarkdown::render("flexdashboard.Rmd", output_format = "flexdashboard::flex_dashboard")
library(flexdashboard)
library(tidyverse)
library(p8105.datasets)
library(plotly)
library(knitr)
```

```{r , include=FALSE, echo = FALSE}
data(instacart)

instacart = 
  instacart |> 
  sample_n(20000)
  # mutate(rating = review_scores_location / 2) |>
  # select(
  #   neighbourhood_group, neighbourhood, rating, price, room_type, lat, long) |>
  # filter(
  #   !is.na(rating), 
  #   neighbourhood_group == "Manhattan",
  #   room_type == "Entire home/apt",
  #   price %in% 100:500)
```

Column {data-width=650}
-----------------------------------------------------------------------

### Chart A

```{r, echo = FALSE}
instacart |> 
  group_by(department, order_dow) |> 
  summarize_at(vars(order_hour_of_day), list(mean_hour = mean)) |> 
  plot_ly(
        x = ~order_dow, y = ~mean_hour, type = "scatter", mode = "lines+markers", color = ~department, colors = "viridis"
  )
# nyc_airbnb |>
#   mutate(text_label = str_c("Price: $", price, "\nRating: ", rating)) |> 
#   plot_ly(
#     x = ~lat, y = ~long, type = "scatter", mode = "markers",
#     color = ~price, text = ~text_label, alpha = 0.5)
```

Column {data-width=350}
-----------------------------------------------------------------------

### Chart B

```{r, echo = FALSE}
instacart |> 
  count(aisle) |> 
  mutate(aisle = fct_reorder(aisle, n)) |> 
  plot_ly(x = ~aisle, y = ~n, color = ~aisle, type = "bar", colors = "viridis")
# nyc_airbnb |> 
#   mutate(neighbourhood = fct_reorder(neighbourhood, price)) |> 
#   plot_ly(y = ~price, color = ~neighbourhood, type = "box", colors = "viridis")
```

### Chart C

```{r, echo = FALSE}
instacart |> 
  plot_ly(x = ~order_dow, y = ~order_hour_of_day, type = "box", colors = "viridis")
# nyc_airbnb |> 
#   count(neighbourhood) |> 
#   mutate(neighbourhood = fct_reorder(neighbourhood, n)) |> 
#   plot_ly(x = ~neighbourhood, y = ~n, color = ~neighbourhood, type = "bar", colors = "viridis")
```

